export default {
    attNegative: `.bg-negative`,
    attActiveFilter: `.filter-active`,
    pageLanding: `[data-cy="pageLanding"]`,
    cardItemsRow: `[data-cy="cardItemsRow"]`,
    cardSearchDropdown: `[data-cy="cardSearchDropdown"]`,
    lblProductItem: `[data-cy="lblProductItem"]`,
    btnSortByPrice: `[data-cy="btnSortByPrice"]`,
    btnSortByPopularity: `[data-cy="landingPage"]`,
    btnAddToCart: `[data-cy="btnAddToCart"]`,
    btnProceed: `[data-cy="btnProceed"]`,
    btnViewCart: `[data-cy="btnViewCart"]`,
    txtSearchProduct: `[data-cy="txtSearchProduct"]`,
    btnSearchProduct: `[data-cy="btnSearchProduct"]`,
    btnCart: `[data-cy="btnCart"]`,
    lblCartQuantity: `[data-cy="btnCart"] span`, //or ideally its own unique id :-)
    lblPositiveToast: `[data-cy="lblPositiveToast"]`,
    lblNegativeToast: `[data-cy="lblPositiveToast"]`,
    lblNegativeHint: `[data-cy="lblNegativeHint"]`,
    cardDialogModalWindowGeneric: `.dialog-modal`,
    lblPagination: `[data-cy="lblPagination"]`,
    lblLoading: `[data-cy="lblLoading"]`,
    lblLoading: `[data-cy="lblLoading"]`,
    cardSidebar: `[data-cy="cardSidebar"]`,
    lblCategory: `[data-cy="lblCategory"]`,
    cardHeader: `[data-cy="cardHeader"]`,
}